name = "WhereTraits"
uuid = "c9d4e05b-6318-49cb-9b56-e0e2b0ceadd8"
authors = ["Sahm Stephan <stephan.sahm@gmx.de>"]
version = "1.0.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DataTypesBasic = "83eed652-29e8-11e9-12da-a7c29d64ffc9"
ExprParsers = "c5caad1f-83bd-4ce8-ac8e-4b29921e994e"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
ProxyInterfaces = "9b3bf0c4-f070-48bc-ae01-f2584e9c23bc"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SimpleMatch = "a3ae8450-d22f-11e9-3fe0-77240e25996f"
StructEquality = "6ec83bb0-ed9f-11e9-3b4c-2b04cb4e219c"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[compat]
Compat = "2.1, 3"
DataTypesBasic = "1.0, 2"
ExprParsers = "1.0"
ProxyInterfaces = "1.0"
Setfield = "0.7"
SimpleMatch = "1.0"
StructEquality = "1.0"
Suppressor = "0.2"
julia = "1.3"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
InteractiveUtils = "b77e0a4c-d291-57a0-90e8-8db25a27a240"
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Documenter", "Test", "StringDistances", "InteractiveUtils"]
